server:
  port: 9527


spring:
  application:
    name: springcloud-zuul



eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: zuul-9527.com
    prefer-ip-address: true


info:
  app.name: com.cj.springcloud
  company.name: www.cj.com
  build.artifactId: springcloud-zuul-9527
  build.version: 1.0-SNAPSHOT


zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: "*"
  prefix: /cj
